#! /usr/bin/perl

use strict;
use warnings;

use Data::Dumper;
use File::Find::Rule;
use Getopt::Long;
use File::Spec;

my $home = $ENV{HOME};

my %options = (
  searchbase => ".",
);

GetOptions (
  'searchbase|base|b=s' => sub {
    my ($optname, $value) = @_;

    if ($value eq 'top') {
      $value = "${home}/imvu";
    }

    $options{searchbase} = File::Spec->rel2abs($value);
  },
) or die ("Error in command line arguments: $!\n");


sub findem {
  my $rule = File::Find::Rule->new;
  $rule->file;
  $rule->not($rule->new->name(qr|^\.|));
  $rule->name(qr|~$|);

  die "no search base" unless -e $options{searchbase};
  my @files = $rule->in($options{searchbase});
  chomp(@files);
  return @files;
}

my @files = findem();
unlink @files;
